### ISSUE TITLE
Configuring distributed KE to expose some services

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#403]
In GitLab by @dominic.ectors.vito.be on Jan 14, 2023, 17:13

Hi Barry,

I'm setting up a KD and KE so I can expose some services to other partners. See [ICT_architecture.pdf](https://gitlab.inesctec.pt/interconnect/knowledge-engine/uploads/0b2a586e586e66e4410bfa0aaf0a4cba/ICT_architecture.pdf)

Some fragment of the compose file:
``` 
##############################################################################################
  # SIF components for exposing services (PV forecaster, weather forecaster, ...)
  ##############################################################################################
  #knowledge directory to let others link their KE to our ke-exposed 
  kd-exposed:
    image: docker-registry.inesctec.pt/interconnect/knowledge-engine/knowledge-directory:1.1.1
    container_name: kd_exposed
    restart: on-failure
    ports:
      - "8190:8282"

  #local knowledge engine to expose the public services
  ke-exposed:
    image: docker-registry.inesctec.pt/interconnect/knowledge-engine/smart-connector-rest-dist:1.1.1
    container_name: ke_exposed
    restart: on-failure
    ports:
      # 8183 port for exposing the Knowledge Engine REST API
      - "8183:8280"
      # 8083 port is for the inter-KER REST API, and container exposed port should be the same as for KE_RUNTIME_PORT
      - "8083:8083"
    environment:
      KD_URL: http://kd-exposed:8282
      KE_RUNTIME_PORT: 8083 
      KE_RUNTIME_EXPOSED_URL:  ke-exposed.interconnect.vito.be:443
```

How does the remote KE know if it should use http or https, because it is not specified in the URL? Is it always https for inter KER communication?

Best regards,
Dominic
