### ISSUE TITLE
No connection possible with KE docker container

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#437]
In GitLab by @cdemulde.openmotics.com on Jul 7, 2023, 09:33

Hi!

We are setting up a local instance of the KE, but are running into some issues. Deploying a docker container on my local machine with the following compose details:

```
  knowledge-engine:
    container_name: knowledge-engine
    image: docker-registry.inesctec.pt/interconnect/knowledge-engine/smart-connector-rest-dist:1.1.3
    ports:
      - 8280:8280
      - 8081:8081
    env_file:
      - env.interconnect
    networks:
       - interconnect
```

answers `curl: (52) Empty reply from server` to `curl localhost:8081`, so the port of the reverse proxy.
On our staging environment, using a similar configuration:

```
knowledge-engine:
    image: "{{ knowledge_engine_image }}:1.1.3"
    container_name: {{ knowledge_engine_name }}
    ports:
      - 8280:8280
      - 8004:8081
    env_file:
      - .env.interconnect
    networks:
       - interconnect
```

a call to `curl localhost:8004` gives `curl: (56) Recv failure: Connection reset by peer`. Just wondering if any of those responses are expected, and if not, what the issue could be.
The container is in both cases correctly started, as localhost:8280/rest/sc returns an empty list and so is reachable without any issues.
