### ISSUE TITLE
In distributive mode, a ‘HTTP/1.1 header parser received no bytes' error occurs during inter-KER communication.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#449]
In GitLab by @barry.nouwt.tno.nl on Nov 16, 2023, 16:38

Why this occurs and the solution is explained in this SO question: https://stackoverflow.com/questions/74215117/flickering-httpclient-sometimes-throwing-ioexception/74233477#74233477

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Nov 16, 2023, 16:40

We have tested this and indeed, setting the keep alive configuration to 3 seconds reduces (or removes) the error from the log files. To configure it, add the following parameter to the JVM starting the Knowledge Engine: `-Djdk.httpclient.keepalive.timeout=3`

When using docker compose, you can configure it like this:
```
runtime-2:
    …
    environment:
      KE_RUNTIME_PORT: …
      KE_RUNTIME_EXPOSED_URL: …
      KD_URL: …
      JAVA_TOOL_OPTIONS: "-Djdk.httpclient.keepalive.timeout=3"
```

The `JAVA_TOOL_OPTIONS` variable is automatically picked up when starting the KER using the official KE Docker images.
