### ISSUE TITLE
Adding two or more SC in separate KERs sometimes should not sometimes cause them to not register the other.

### ISSUE THREAD

**Issue by bnouwt** [TNO/knowledge-engine#551]
In the TDI-500 docker compose project, a race condition seemed to occur where three knowledge mappers started up at the same time and registered their smart connector (in separate KERs) at the same time and this sometimes caused them to miss the registration of the other and this did not automatically fix itself after some time.

We think this is caused by a timing issue where SC A asks (at startup) which other SCs are already in the network and gets no response from SC B because SC B is not yet fully started. This should not  be a problem, because every SC should notify all others of its existence by using a Post KI, but when SC B posts this notification SC A is not yet ready to receive this message and also does not register SC B in that way. So, SC A will never know that SC B exists.

There have been issues with this before that were partly fixed, but apparently it is not fully fixed. There is a workaround that @kadevgraaf-tno can attach to this issue, until we have fixed the underlying issue of SC startup.

**Comment by kadevgraaf-tno** [comment]
I think I have a workaround by using Docker healthcheck and depends_on for starting knowledge mappers in succession/sequentially:
 
```
services:
  kd:
    image: ghcr.io/tno/knowledge-engine/knowledge-directory:1.2.3
 
  daikin-km:
    build: ./daikin-km
    environment:
      - DAIKIN_CLIENT_ID
      - DAIKIN_CLIENT_SECRET
      - DAIKIN_REFRESH_TOKEN
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://daikin-sc:8280/rest/sc"]
        interval: 10s
        timeout: 5s
        retries: 5      
 
  daikin-sc:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.2.4
    environment:
      HOSTNAME: daikin-sc
      PORT: 8081 # The (knowledge engine internal) port that is used for inter-runtime communication
      KE_RUNTIME_EXPOSED_URL: http://daikin-sc:8081/
      KE_RUNTIME_PORT: 8081
      KD_URL: http://kd:8282/
    restart: always          
 
  triplesolar-km:
    build: ./triplesolar-km
    environment:
      - TS_EMAIL
      - TS_PASSWORD
      - INTERFACE_ID
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://triplesolar-sc:8280/rest/sc"]
        interval: 10s
        timeout: 5s
        retries: 5        
    depends_on:
      daikin-km:
        condition: service_healthy
 
  triplesolar-sc:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.2.4
    environment:
      HOSTNAME: triplesolar-sc
      PORT: 8081 # The (knowledge engine internal) port that is used for inter-runtime communication
      KE_RUNTIME_EXPOSED_URL: http://triplesolar-sc:8081/
      KE_RUNTIME_PORT: 8081
      KD_URL: http://kd:8282/
    restart: always
    depends_on:
      daikin-km:
        condition: service_healthy      
 
  intergas-km:
    build: ./intergas-km
    environment:
      - INTERGAS_ACCESS_TOKEN
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://intergas-sc:8280/rest/sc"]
        interval: 10s
        timeout: 5s
        retries: 5        
    depends_on:
      triplesolar-km:
        condition: service_healthy
       
 
  intergas-sc:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.2.4
    environment:
      HOSTNAME: intergas-sc
      PORT: 8081 # The (knowledge engine internal) port that is used for inter-runtime communication
      KE_RUNTIME_EXPOSED_URL: http://intergas-sc:8081/
      KE_RUNTIME_PORT: 8081
      KD_URL: http://kd:8282/
    restart: always
    depends_on:
      triplesolar-km:
        condition: service_healthy      
     
  vaillant-km:
    build: ./vaillant-km
    environment:
      - VAILLANT_CLIENT_ID
      - VAILLANT_SECRET
      - VAILLANT_REFRESH_TOKEN
      - VAILLANT_SUBSCRIPTION_KEY
    restart: always
    depends_on:
      intergas-km:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://intergas-sc:8280/rest/sc"]
        interval: 10s
        timeout: 5s
        retries: 5          
 
  vaillant-sc:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.2.4
    environment:
      HOSTNAME: vaillant-sc
      PORT: 8081 # The (knowledge engine internal) port that is used for inter-runtime communication
      KE_RUNTIME_EXPOSED_URL: http://vaillant-sc:8081/
      KE_RUNTIME_PORT: 8081
      KD_URL: http://kd:8282/
    restart: always
    depends_on:
      intergas-km:
        condition: service_healthy
```
